TodoApplication.Web/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TodoApplication.Domain.Enums;
using TodoApplication.Web.Models.Repositories;

namespace TodoApplication.Web.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly ITodoTaskRepository _todoTaskRepository;

        public NavigationMenuViewComponent(ITodoTaskRepository todoTaskRepository)
        {
            _todoTaskRepository = todoTaskRepository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.CompletedCategory = _todoTaskRepository.GetAllTasks()
                .Where(p => p.Status == Status.Completed);

            ViewBag.CountOfCompletedTaks = _todoTaskRepository.GetAllTasks()
                .Where(p => p.Status == Status.Completed)
                .Count();

            ViewBag.SelectedCategory = RouteData?.Values["list"];
            return View(_todoTaskRepository.GetAllTasks()
               .Select(x => x.List)
               .Distinct()
               .OrderBy(x => x));
        }
    }
}

TodoApplication.Web/Controllers/TodoTasksController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System;
using TodoApplication.Domain.Entities;
using TodoApplication.Web.Models.Repositories;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TodoApplication.Web.Controllers
{
    public class TodoTasksController : Controller
    {
        private readonly ITodoTaskRepository _todoTaskRepository;
        private readonly ITodoListRepository _todoListRepository;

        public TodoTasksController(ITodoTaskRepository todoTaskRepository, ITodoListRepository todoListRepository)
        {
            _todoTaskRepository = todoTaskRepository;
            _todoListRepository = todoListRepository;
        }

        public IActionResult Create()
        {
            var todoLists = _todoListRepository.GetAllLists(); 

            ViewBag.TodoLists = todoLists;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Title,Description,Status,IsImportant,IsPlanned,DueTime,ListId")] TodoTask todoTask)
        {
            if (!ModelState.IsValid)
            {
                throw new Exception("Task is not valid.");
            }

            var todoList = _todoListRepository.GetAllLists()
                .FirstOrDefault(p => p.Id == todoTask.ListId);
            if (todoList is null)
                throw new Exception("List title is not true.");

            todoList.CountOfTasks += 1;
            todoList.CreatedAt = DateTime.UtcNow;
            await _todoListRepository.UpdateAsync(todoList);

            todoTask.ListId = todoList.Id;
            await _todoTaskRepository.CreateAsync(todoTask);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var todoLists = _todoListRepository.GetAllLists();

            ViewBag.TodoLists = todoLists;

            var product = await _todoTaskRepository.GetByIdAsync(id);
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TodoTask todoTask)
        {
            if (!ModelState.IsValid)
                return View(todoTask);

            if (string.IsNullOrWhiteSpace(todoTask.Title))
                return View(todoTask);

            var existTask = await _todoTaskRepository.GetByIdAsync(id);
            if (existTask is null)
                throw new Exception("TodoList not found.");
            
            if  (existTask.ListId != todoTask.ListId)
            {
                var lastList = await _todoListRepository.GetAllLists()
                    .FirstOrDefaultAsync(p => p.Id == existTask.ListId);
                lastList.CountOfTasks -= 1;
                await _todoListRepository.UpdateAsync(lastList);

                var newList = await _todoListRepository.GetAllLists()
                    .FirstOrDefaultAsync(p => p.Id == todoTask.ListId);
                newList.CountOfTasks += 1;
                await _todoListRepository.UpdateAsync(newList);
            }

            existTask.Title = todoTask.Title;
            existTask.Description = todoTask.Description;
            existTask.Status = todoTask.Status;
            existTask.IsImportant = todoTask.IsImportant;
            existTask.IsPlanned = todoTask.IsPlanned;
            existTask.DueTime = todoTask.DueTime;
            existTask.ListId = todoTask.ListId;
            existTask.CreatedAt = existTask.CreatedAt;
            existTask.UpdatedAt = DateTime.UtcNow;
            await _todoTaskRepository.UpdateAsync(existTask);
            return RedirectToAction("Index", "Home");
        }
    }
}

TodoApplication.Web/Views/Shared/TodoTaskSummary.cshtml
@using TodoApplication.Web.Infrastructure;
@model TodoTask

<ul class="ul-list">
    <li>
        <div class="content">
            <label class="checkbox-container">
            </label>
            <div class="box">
                <h1>@Html.ActionLink(Model.Title, "Edit", "TodoTasks", new { id = Model.Id }, null)</h1>
                <div class="description">
                    <div>
                        <img src="https://cdn-icons-png.flaticon.com/512/2222/2222384.png" alt="">
                        <p>@Model.Status</p>
                    </div>
                    <div>
                        <img src="https://cdn-icons-png.flaticon.com/512/833/833593.png" alt="">
                        @if (Model.IsPlanned)
                        {
                            <p>@Model.DueTime</p>
                        }
                        else
                        {
                            <p>not planned</p>
                        }
                    </div>
                    <div>
                        @if (Model.IsImportant)
                        {
                            <img src="https://cdn-icons-png.flaticon.com/512/1827/1827422.png" alt="">
                            <p>Important</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </li>
</ul>

TodoApplication.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To Do</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <div class="bg-primary text-white p-2">
        <span class="navbar-brand ml-2">To Do</span>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:navigation-menu />
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>